import { Language, OnboardingTourConfig } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// TRANSLATIONS — All text for all 14 onboarding tours in 7 languages
// ─────────────────────────────────────────────────────────────────────────────
const T: Record<Language, {
  welcomeTitle: string; welcomeDesc: string;
  w1Title: string; w1Content: string; w1Badge: string;
  w2Title: string; w2Content: string; w2Badge: string;
  w3Title: string; w3Content: string; w3Badge: string;
  w4Title: string; w4Content: string; w4Badge: string;
  interfacesTitle: string; interfacesDesc: string;
  i1Title: string; i1Content: string;
  i2Title: string; i2Content: string;
  profilesTitle: string; profilesDesc: string;
  p1Title: string; p1Content: string;
  p2Title: string; p2Content: string;
  quickipTitle: string; quickipDesc: string;
  q1Title: string; q1Content: string;
  q2Title: string; q2Content: string;
  connectivityTitle: string; connectivityDesc: string;
  c1Title: string; c1Content: string;
  c2Title: string; c2Content: string;
  scannerTitle: string; scannerDesc: string;
  s1Title: string; s1Content: string;
  s2Title: string; s2Content: string;
  s3Title: string; s3Content: string;
  credentialsTitle: string; credentialsDesc: string;
  cr1Title: string; cr1Content: string;
  cr2Title: string; cr2Content: string;
  clipboardTitle: string; clipboardDesc: string;
  cl1Title: string; cl1Content: string;
  internetTitle: string; internetDesc: string;
  in1Title: string; in1Content: string;
  portTitle: string; portDesc: string;
  po1Title: string; po1Content: string;
  traceTitle: string; traceDesc: string;
  tr1Title: string; tr1Content: string;
  systemTitle: string; systemDesc: string;
  sy1Title: string; sy1Content: string;
  eventsTitle: string; eventsDesc: string;
  ev1Title: string; ev1Content: string;
  shortcutsTitle: string; shortcutsDesc: string;
  sh1Title: string; sh1Content: string;
}> = {

  // ── ESPAÑOL ──────────────────────────────────────────────────────────────────
  es: {
    welcomeTitle: '👋 Bienvenido a NetMajik',
    welcomeDesc: 'Aprende los conceptos fundamentales y cómo cambiar entre Modo Básico y Avanzado.',
    w1Title: '1. Modos de Trabajo: Básico vs Avanzado',
    w1Content: 'El **Modo Básico** te ofrece una interfaz limpia y segura con las herramientas del día a día (Ping, Escáner, Credenciales e Interfaces). El **Modo Avanzado** activa herramientas especializadas como escaneo de puertos, traceroute y visor de eventos.',
    w1Badge: 'Control de Modo',
    w2Title: '2. Estado de tus Conexiones',
    w2Content: 'Aquí verás todas tus tarjetas de red (Ethernet y Wi-Fi), su IP actual y, lo más importante: **qué perfil de red tienen asignado** o si están en modo Automático (DHCP).',
    w2Badge: 'Interfaces',
    w3Title: '3. Herramientas Rápidas',
    w3Content: 'Navega rápidamente entre el diagnóstico de red, escáner de dispositivos, credenciales de equipos y portapapeles con un solo clic.',
    w3Badge: 'Navegación',
    w4Title: '4. Búsqueda Global (Ctrl+K)',
    w4Content: 'Pulsa Ctrl+K o este botón en cualquier momento para encontrar cualquier perfil, IP, equipo o credencial al instante.',
    w4Badge: 'Productividad',
    interfacesTitle: '🌐 Interfaces y Perfil Activo',
    interfacesDesc: 'Cómo identificar adaptadores, comprobar enlace y saber qué perfil está activo.',
    i1Title: 'Tus Tarjetas de Red',
    i1Content: 'Cada tarjeta muestra un indicador verde si está conectada a la red o gris si el cable está desconectado.',
    i2Title: 'Perfil Activo',
    i2Content: 'Te indica al instante si tu tarjeta está en "DHCP (Automático)" o utilizando un perfil fijo como "Cámaras", "Planta 1", etc.',
    profilesTitle: '⚡ Perfiles de Red y DHCP',
    profilesDesc: 'Aprende a cambiar de configuración de red en 1 clic y volver a DHCP sin esfuerzo.',
    p1Title: 'Lista de Perfiles Guardados',
    p1Content: 'Haz clic en "Aplicar" en cualquier perfil para configurar tu tarjeta de red al instante con esa IP, máscara y puerta de enlace.',
    p2Title: 'Crear Nuevo Perfil',
    p2Content: 'Guarda las IPs que usas habitualmente en clientes o instalaciones para no tener que recordarlas ni escribirlas a mano.',
    quickipTitle: '🎯 Asignación Rápida de IP (Quick IP)',
    quickipDesc: 'Configura una IP estática en 5 segundos para pruebas puntuales.',
    q1Title: 'Panel de IP Rápida',
    q1Content: 'Escribe directamente la IP deseada (por ejemplo 192.168.1.50) y pulsa Enter o "Aplicar Rápido" para fijarla en tu tarjeta en segundos.',
    q2Title: 'Búsqueda de IP Libre en 1 Clic',
    q2Content: 'Pulsa un rango predefinido para que NetMajik escanee el segmento mediante ARP, encuentre una IP libre que nadie esté usando y te la asigne automáticamente.',
    connectivityTitle: '🩺 Diagnóstico Ping y Conexión',
    connectivityDesc: 'Comprueba si un equipo o router responde con diagnósticos en lenguaje claro.',
    c1Title: 'Introducir IP o Nombre de Equipo',
    c1Content: 'Escribe la IP (ej: 192.168.1.1 o google.com) o pulsa "Pegar y Probar" para comprobar inmediatamente si el equipo responde.',
    c2Title: 'Semáforo y Estado Comprensible',
    c2Content: 'Un distintivo verde indica conexión perfecta con su tiempo de respuesta en milisegundos. Si falla, verás claramente si el equipo está apagado o fuera de rango.',
    scannerTitle: '🔍 Descubrimiento de Red (Scanner)',
    scannerDesc: 'Descubre todos los aparatos de la red, sus nombres y fabricantes.',
    s1Title: 'Escanear Red en 1 Clic',
    s1Content: 'NetMajik calcula automáticamente el rango de tu subred. Solo pulsa el botón para buscar todos los dispositivos conectados.',
    s2Title: 'Resultados Claros y Fabricantes',
    s2Content: 'Identifica rápidamente cámaras Hikvision/Dahua, routers Cisco/MikroTik, teléfonos y ordenadores gracias a la base de datos de fabricantes OUI.',
    s3Title: 'Copiar y Acciones Rápidas',
    s3Content: 'Pasa el ratón por cualquier fila para copiar la IP o MAC con un clic, o enviarla directamente al Ping o Escáner de Puertos.',
    credentialsTitle: '🔑 Librería de Credenciales',
    credentialsDesc: 'Consulta usuarios y contraseñas de routers y equipos con total seguridad.',
    cr1Title: 'Búsqueda Instantánea',
    cr1Content: 'Busca por marca (MikroTik, Ubiquiti, Cisco...), modelo o IP por defecto para encontrar sus accesos habituales.',
    cr2Title: 'Seguridad y Copiado Rápido',
    cr2Content: 'Las contraseñas se ocultan con puntos por privacidad. Puedes pulsar "Copiar Usuario" o "Copiar Contraseña" para pegarlas directamente en la web del equipo.',
    clipboardTitle: '📋 Portapapeles Inteligente (Snippets)',
    clipboardDesc: 'Almacena comandos, textos e IPs de uso frecuente para ahorrar tiempo.',
    cl1Title: 'Tus Textos Frecuentes',
    cl1Content: 'Haz clic sobre cualquier tarjeta de snippet para copiar su texto al portapapeles al instante.',
    internetTitle: '🌐 Estado de Salida a Internet',
    internetDesc: 'Verifica si el router tiene salida al exterior, tu IP pública y tu proveedor.',
    in1Title: 'Diagnóstico WAN Completo',
    in1Content: 'Comprueba si puedes navegar, tu latencia hacia DNS raíz (Google, Cloudflare) y los datos de tu operador (ISP).',
    portTitle: '🛡️ Escáner de Puertos y Servicios',
    portDesc: 'Descubre qué servicios (Web, SSH, RTSP, Bases de Datos) tiene abiertos un equipo.',
    po1Title: 'Presets de Puertos Habituales',
    po1Content: 'Selecciona presets rápidos como Web (80/443), CCTV/Cámaras (554/8000/37777), Administración (SSH/RDP) o introduce un rango personalizado.',
    traceTitle: '🗺️ Trazado de Rutas (Traceroute)',
    traceDesc: 'Descubre en qué salto de red se produce un corte o cuello de botella.',
    tr1Title: 'Pestaña Traceroute',
    tr1Content: 'En el Modo Avanzado, la zona de conectividad incluye Traceroute para rastrear cada router intermedio hasta el destino.',
    systemTitle: '💻 Salud del PC y Hardware',
    systemDesc: 'Monitoriza procesador, uso de memoria, discos duros y temperaturas.',
    sy1Title: 'Métricas de Hardware en Vivo',
    sy1Content: 'Consulta el rendimiento de tu equipo y detecta cuellos de botella de hardware mientras trabajas.',
    eventsTitle: '⚠️ Visor de Errores y Eventos Windows',
    eventsDesc: 'Detecta fallos de disco, cuelgues de controladores o errores críticos de Windows.',
    ev1Title: 'Registro de Fallos del Sistema',
    ev1Content: 'Filtra eventos críticos para diagnosticar problemas de hardware antes de que causen una avería mayor.',
    shortcutsTitle: '⚙️ Funciones de Windows y Scripts',
    shortcutsDesc: 'Ejecuta limpieza de DNS, reset de Winsock y abre consolas del sistema en 1 clic.',
    sh1Title: 'Scripts y Consolas de Windows',
    sh1Content: 'Accede directamente a ncpa.cpl, Administración de Dispositivos, Firewall o ejecuta ipconfig /flushdns y netsh winsock reset sin abrir la consola CMD.',
  },

  // ── ENGLISH ──────────────────────────────────────────────────────────────────
  en: {
    welcomeTitle: '👋 Welcome to NetMajik',
    welcomeDesc: 'Learn the core concepts and how to switch between Basic and Advanced modes.',
    w1Title: '1. Working Modes: Basic vs Advanced',
    w1Content: 'The **Basic Mode** provides a clean, safe workspace with essential daily tools (Ping, Scanner, Credentials, Interfaces). The **Advanced Mode** unlocks deep network tools like port scanners, traceroute, and event viewer.',
    w1Badge: 'Mode Control',
    w2Title: '2. Connection Status',
    w2Content: 'Here you see all network adapters (Ethernet & Wi-Fi), current IP, and most importantly: **which network profile is active** or if DHCP is set.',
    w2Badge: 'Adapters',
    w3Title: '3. Quick Tools',
    w3Content: 'Navigate rapidly between ping diagnostics, device discovery, equipment credentials, and clipboard snippets with one click.',
    w3Badge: 'Navigation',
    w4Title: '4. Global Search (Ctrl+K)',
    w4Content: 'Press Ctrl+K or this button anytime to find any profile, IP, device, or credential instantly.',
    w4Badge: 'Productivity',
    interfacesTitle: '🌐 Interfaces & Active Profile',
    interfacesDesc: 'How to identify network adapters, verify link status, and check active profile.',
    i1Title: 'Your Network Adapters',
    i1Content: 'Each card displays a green badge when connected or gray when disconnected.',
    i2Title: 'Active Profile',
    i2Content: 'Instantly tells you if your interface is on "DHCP (Auto)" or using a static profile like "Cameras", "Floor 1", etc.',
    profilesTitle: '⚡ Network Profiles & DHCP',
    profilesDesc: 'Learn to switch network configurations in 1 click and return to DHCP effortlessly.',
    p1Title: 'Saved Profiles List',
    p1Content: 'Click "Apply" on any profile to configure your adapter with that IP, netmask, and gateway.',
    p2Title: 'Create New Profile',
    p2Content: 'Save frequently used IPs for clients or sites so you never have to remember or retype them manually.',
    quickipTitle: '🎯 Quick IP Assignment',
    quickipDesc: 'Set a static IP in 5 seconds for temporary testing.',
    q1Title: 'Quick IP Panel',
    q1Content: 'Type the desired IP (e.g. 192.168.1.50) and press Enter or "Quick Apply" to set it in seconds.',
    q2Title: '1-Click Free IP Search',
    q2Content: 'Click a preset range to let NetMajik scan ARP, find an unused free IP, and assign it to you automatically.',
    connectivityTitle: '🩺 Ping & Connection Diagnostics',
    connectivityDesc: 'Test if a host or router responds with clear language feedback.',
    c1Title: 'Enter IP or Hostname',
    c1Content: 'Type the IP (e.g. 192.168.1.1 or google.com) or click "Paste & Test" to check response immediately.',
    c2Title: 'Clear Traffic Light Status',
    c2Content: 'A green badge indicates optimal response time in ms. If it fails, you see clearly whether the host is offline or unreachable.',
    scannerTitle: '🔍 Network Discovery (Scanner)',
    scannerDesc: 'Discover all network devices, hostnames, and MAC vendors.',
    s1Title: '1-Click Network Scan',
    s1Content: 'NetMajik calculates your subnet range automatically. Click scan to discover all live devices.',
    s2Title: 'Vendor Identification',
    s2Content: 'Identify Hikvision/Dahua cameras, Cisco/MikroTik routers, phones, and PCs using IEEE OUI vendor database.',
    s3Title: 'Quick Copy & Actions',
    s3Content: 'Hover over any row to copy IP/MAC with one click or send to Ping/Port Scanner.',
    credentialsTitle: '🔑 Credential Library',
    credentialsDesc: 'Look up default logins for routers and equipment safely.',
    cr1Title: 'Instant Search',
    cr1Content: 'Search by brand (MikroTik, Ubiquiti, Cisco...), model, or default IP.',
    cr2Title: 'Security & Fast Copy',
    cr2Content: 'Passwords are masked with bullets for privacy. Click "Copy User" or "Copy Password" to paste into device web UI.',
    clipboardTitle: '📋 Smart Clipboard Snippets',
    clipboardDesc: 'Store frequent commands, texts, and IPs to save time.',
    cl1Title: 'Your Frequent Texts',
    cl1Content: 'Click any snippet card to copy its content to clipboard instantly.',
    internetTitle: '🌐 Internet Outlet Status',
    internetDesc: 'Verify router WAN connection, public IP, and ISP provider.',
    in1Title: 'Full WAN Diagnostics',
    in1Content: 'Check internet reachability, root DNS latency (Google, Cloudflare), and ISP details.',
    portTitle: '🛡️ Port & Service Scanner',
    portDesc: 'Discover open ports and active services (Web, SSH, RTSP, DB).',
    po1Title: 'Common Port Presets',
    po1Content: 'Select quick presets for Web (80/443), CCTV (554/8000), Admin (SSH/RDP), or custom ranges.',
    traceTitle: '🗺️ Route Tracing (Traceroute)',
    traceDesc: 'Discover where packet loss or latency spikes happen across hops.',
    tr1Title: 'Traceroute Tab',
    tr1Content: 'Advanced mode includes Traceroute to trace intermediate routers to your destination.',
    systemTitle: '💻 PC Health & Hardware',
    systemDesc: 'Monitor CPU load, memory usage, disk health, and system uptime.',
    sy1Title: 'Live Hardware Metrics',
    sy1Content: 'Monitor live system performance and spot hardware bottlenecks.',
    eventsTitle: '⚠️ Windows Event & Error Log',
    eventsDesc: 'Detect disk errors, driver crashes, and critical Windows events.',
    ev1Title: 'System Failure Log',
    ev1Content: 'Filter critical events to diagnose hardware issues before severe failure.',
    shortcutsTitle: '⚙️ Windows Features & Scripts',
    shortcutsDesc: 'Run DNS flush, Winsock reset, and open system management consoles in 1 click.',
    sh1Title: 'Windows Consoles & Scripts',
    sh1Content: 'Direct access to ncpa.cpl, Device Manager, Firewall, or run ipconfig /flushdns and netsh winsock reset.',
  },

  // ── PORTUGUÊS ────────────────────────────────────────────────────────────────
  pt: {
    welcomeTitle: '👋 Bem-vindo ao NetMajik',
    welcomeDesc: 'Aprenda os conceitos fundamentais e como alternar entre o Modo Básico e o Avançado.',
    w1Title: '1. Modos de Trabalho: Básico vs Avançado',
    w1Content: 'O **Modo Básico** oferece uma interface limpa e segura com as ferramentas do dia a dia (Ping, Scanner, Credenciais e Interfaces). O **Modo Avançado** ativa ferramentas especializadas como scanner de portas, traceroute e visualizador de eventos.',
    w1Badge: 'Controle de Modo',
    w2Title: '2. Status de Conexão',
    w2Content: 'Aqui você vê todas as suas placas de rede (Ethernet e Wi-Fi), IP atual e qual perfil está ativo.',
    w2Badge: 'Interfaces',
    w3Title: '3. Ferramentas Rápidas',
    w3Content: 'Navegue rapidamente entre diagnóstico de rede, scanner, credenciais e área de transferência.',
    w3Badge: 'Navegação',
    w4Title: '4. Busca Global (Ctrl+K)',
    w4Content: 'Pressione Ctrl+K para encontrar qualquer perfil, IP ou equipamento instantaneamente.',
    w4Badge: 'Produtividade',
    interfacesTitle: '🌐 Interfaces e Perfil Ativo',
    interfacesDesc: 'Como identificar adaptadores e verificar perfil ativo.',
    i1Title: 'Placas de Rede',
    i1Content: 'Cada placa exibe um indicador verde quando conectada.',
    i2Title: 'Perfil Ativo',
    i2Content: 'Informa instantaneamente se está em DHCP ou perfil estático.',
    profilesTitle: '⚡ Perfis de Rede e DHCP',
    profilesDesc: 'Alterne configurações de rede em 1 clique.',
    p1Title: 'Lista de Perfis',
    p1Content: 'Clique em Aplicar para configurar a placa com IP e gateway salvos.',
    p2Title: 'Criar Novo Perfil',
    p2Content: 'Salve IPs frequentes para não precisar digitar manualmente.',
    quickipTitle: '🎯 Atribuição Rápida de IP',
    quickipDesc: 'Configure IP estático em segundos.',
    q1Title: 'Painel de IP Rápido',
    q1Content: 'Digite o IP desejado e aplique instantaneamente.',
    q2Title: 'Busca de IP Livre',
    q2Content: 'NetMajik escaneia via ARP e atribui um IP livre automaticamente.',
    connectivityTitle: '🩺 Diagnóstico de Ping',
    connectivityDesc: 'Verifique se equipamentos respondem com diagnósticos claros.',
    c1Title: 'Inserir IP ou Hostname',
    c1Content: 'Digite o IP ou hostname para testar a resposta imediatamente.',
    c2Title: 'Status Claro',
    c2Content: 'Badge verde indica tempo de resposta ótimo em ms.',
    scannerTitle: '🔍 Descoberta de Rede',
    scannerDesc: 'Descubra dispositivos e fabricantes na rede.',
    s1Title: 'Varredura em 1 Clique',
    s1Content: 'Calcula a sub-rede e busca dispositivos ativos.',
    s2Title: 'Identificação de Fabricante',
    s2Content: 'Identifique câmeras, roteadores e PCs com base OUI.',
    s3Title: 'Cópia Rápida',
    s3Content: 'Passe o mouse para copiar IP/MAC ou enviar ao Ping.',
    credentialsTitle: '🔑 Biblioteca de Credenciais',
    credentialsDesc: 'Consulte senhas padrão de equipamentos com segurança.',
    cr1Title: 'Busca Instantânea',
    cr1Content: 'Busque por marca, modelo ou IP padrão.',
    cr2Title: 'Segurança e Cópia',
    cr2Content: 'Senhas mascaradas por privacidade com botões de cópia rápida.',
    clipboardTitle: '📋 Área de Transferência Inteligente',
    clipboardDesc: 'Armazene comandos e textos frequentes.',
    cl1Title: 'Textos Frequentes',
    cl1Content: 'Clique para copiar o texto instantaneamente.',
    internetTitle: '🌐 Saída de Internet',
    internetDesc: 'Verifique status WAN, IP público e provedor.',
    in1Title: 'Diagnóstico WAN',
    in1Content: 'Teste conectividade externa e latência de DNS.',
    portTitle: '🛡️ Scanner de Portas',
    portDesc: 'Descubra portas e serviços abertos.',
    po1Title: 'Presets de Portas',
    po1Content: 'Selecione presets para Web, CCTV ou Admin.',
    traceTitle: '🗺️ Rastreamento de Rota',
    traceDesc: 'Descubra onde ocorrem perdas de pacotes.',
    tr1Title: 'Aba Traceroute',
    tr1Content: 'Rastreie roteadores intermediários até o destino.',
    systemTitle: '💻 Saúde do Sistema',
    systemDesc: 'Monitore CPU, memória e discos.',
    sy1Title: 'Métricas de Hardware',
    sy1Content: 'Acompanhe desempenho em tempo real.',
    eventsTitle: '⚠️ Visualizador de Eventos',
    eventsDesc: 'Detecte erros de disco e falhas do Windows.',
    ev1Title: 'Registro de Falhas',
    ev1Content: 'Filtre eventos críticos para diagnosticar problemas.',
    shortcutsTitle: '⚙️ Atalhos e Scripts Windows',
    shortcutsDesc: 'Execute flushdns, reset de Winsock e abra ferramentas do Windows.',
    sh1Title: 'Ferramentas de Sistema',
    sh1Content: 'Acesso direto a ncpa.cpl, Gerenciador de Dispositivos e scripts.',
  },

  // ── DEUTSCH ──────────────────────────────────────────────────────────────────
  de: {
    welcomeTitle: '👋 Willkommen bei NetMajik',
    welcomeDesc: 'Lernen Sie die Grundkonzepte und den Wechsel zwischen Basis- und Erweiterter Modus.',
    w1Title: '1. Arbeitsmodi: Basis vs Erweitert',
    w1Content: 'Der **Basis-Modus** bietet eine saubere Oberfläche für tägliche Aufgaben. Der **Erweiterte Modus** schaltet Portscanner und Event-Viewer frei.',
    w1Badge: 'Modus-Steuerung',
    w2Title: '2. Verbindungsstatus',
    w2Content: 'Hier sehen Sie Netzwerkkarten, aktuelle IP und das aktive Profil.',
    w2Badge: 'Adapter',
    w3Title: '3. Schnelle Werkzeuge',
    w3Content: 'Wechseln Sie schnell zwischen Ping, Scanner, Anmeldedaten und Zwischenablage.',
    w3Badge: 'Navigation',
    w4Title: '4. Globale Suche (Strg+K)',
    w4Content: 'Drücken Sie Strg+K um Profile, IPs oder Geräte sofort zu finden.',
    w4Badge: 'Produktivität',
    interfacesTitle: '🌐 Schnittstellen & Aktives Profil',
    interfacesDesc: 'Netzwerkadapter identifizieren und aktives Profil prüfen.',
    i1Title: 'Netzwerkadapter',
    i1Content: 'Grüne Anzeige bei aktiver Verbindung.',
    i2Title: 'Aktives Profil',
    i2Content: 'Zeigt sofort ob DHCP oder ein statisches Profil aktiv ist.',
    profilesTitle: '⚡ Netzwerkprofile & DHCP',
    profilesDesc: 'Netzwerkeinstellungen mit 1 Klick wechseln.',
    p1Title: 'Gespeicherte Profile',
    p1Content: 'Klicken Sie auf Anwenden um IP und Gateway zu setzen.',
    p2Title: 'Neues Profil erstellen',
    p2Content: 'Speichern Sie häufig genutzte IPs für Kunden.',
    quickipTitle: '🎯 Schnelle IP-Zuweisung',
    quickipDesc: 'Statische IP in 5 Sekunden festlegen.',
    q1Title: 'Schnell-IP Panel',
    q1Content: 'Wunsch-IP eingeben und sofort anwenden.',
    q2Title: 'Freie IP-Suche',
    q2Content: 'Scannt ARP und weist eine freie IP automatisch zu.',
    connectivityTitle: '🩺 Ping-Diagnose',
    connectivityDesc: 'Prüfen Sie ob Geräte antworten.',
    c1Title: 'IP oder Hostname eingeben',
    c1Content: 'IP eingeben und Antwortzeit sofort prüfen.',
    c2Title: 'Klarer Status',
    c2Content: 'Grüner Badge zeigt optimale Antwortzeit in ms.',
    scannerTitle: '🔍 Netzwerk-Erkennung',
    scannerDesc: 'Geräte und Hersteller im Netzwerk entdecken.',
    s1Title: '1-Klick Netzwerk-Scan',
    s1Content: 'Berechnet Subnetz und sucht aktive Geräte.',
    s2Title: 'Hersteller-Erkennung',
    s2Content: 'Erkennt Kameras, Router und PCs via OUI-Datenbank.',
    s3Title: 'Schnell-Kopie',
    s3Content: 'IP/MAC mit einem Klick kopieren.',
    credentialsTitle: '🔑 Anmeldedaten-Bibliothek',
    credentialsDesc: 'Standard-Zugangsdaten sicher nachschlagen.',
    cr1Title: 'Sofort-Suche',
    cr1Content: 'Nach Marke, Modell oder Standard-IP suchen.',
    cr2Title: 'Sicherheit & Kopieren',
    cr2Content: 'Passwörter geschützt mit Schnell-Kopier-Buttons.',
    clipboardTitle: '📋 Intelligente Zwischenablage',
    clipboardDesc: 'Häufige Befehle und Texte speichern.',
    cl1Title: 'Häufige Texte',
    cl1Content: 'Klicken um Inhalt sofort zu kopieren.',
    internetTitle: '🌐 Internet-Status',
    internetDesc: 'WAN-Verbindung, öffentliche IP und ISP prüfen.',
    in1Title: 'WAN-Diagnose',
    in1Content: 'Erreichbarkeit und DNS-Latenz prüfen.',
    portTitle: '🛡️ Port-Scanner',
    portDesc: 'Offene Ports und Dienste entdecken.',
    po1Title: 'Port-Voreinstellungen',
    po1Content: 'Presets für Web, CCTV oder Admin wählen.',
    traceTitle: '🗺️ Routenverfolgung',
    traceDesc: 'Engpässe im Netzwerk aufspüren.',
    tr1Title: 'Traceroute Tab',
    tr1Content: 'Routen zu Zwischen-Routern verfolgen.',
    systemTitle: '💻 Systemstatus',
    systemDesc: 'CPU, Speicher und Disks überwachen.',
    sy1Title: 'Hardware-Metriken',
    sy1Content: 'Echtzeit-Leistung des PCs prüfen.',
    eventsTitle: '⚠️ Ereignisanzeige',
    eventsDesc: 'Fehler im Windows-Protokoll erkennen.',
    ev1Title: 'Systemfehler-Protokoll',
    ev1Content: 'Kritische Ereignisse filtern.',
    shortcutsTitle: '⚙️ Windows-Befehle & Scripts',
    shortcutsDesc: 'DNS leeren, Winsock zurücksetzen und Konsolen öffnen.',
    sh1Title: 'Windows-Werkzeuge',
    sh1Content: 'Direkter Zugriff auf ncpa.cpl und Systemskripte.',
  },

  // ── FRANÇAIS ─────────────────────────────────────────────────────────────────
  fr: {
    welcomeTitle: '👋 Bienvenue sur NetMajik',
    welcomeDesc: 'Apprenez les concepts clés et le basculement entre Mode De Base et Avancé.',
    w1Title: '1. Modes de Travail: De Base vs Avancé',
    w1Content: 'Le **Mode De Base** offre une interface simple pour le quotidien. Le **Mode Avancé** débloque le scanner de ports et le journal d évènements.',
    w1Badge: 'Contrôle du Mode',
    w2Title: '2. État des Connexions',
    w2Content: 'Consultez vos cartes réseau, IP actuelle et profil actif.',
    w2Badge: 'Interfaces',
    w3Title: '3. Outils Rapides',
    w3Content: 'Basculez rapidement entre Ping, Scanner, Identifiants et Presse-papiers.',
    w3Badge: 'Navigation',
    w4Title: '4. Recherche Globale (Ctrl+K)',
    w4Content: 'Appuyez sur Ctrl+K pour trouver un profil, une IP ou un équipement.',
    w4Badge: 'Productivité',
    interfacesTitle: '🌐 Interfaces et Profil Actif',
    interfacesDesc: 'Identifier les cartes réseau et vérifier le profil actif.',
    i1Title: 'Cartes Réseau',
    i1Content: 'Indicateur vert lorsque la carte est connectée.',
    i2Title: 'Profil Actif',
    i2Content: 'Indique si vous êtes en DHCP ou profil fixe.',
    profilesTitle: '⚡ Profils Réseau et DHCP',
    profilesDesc: 'Changez de configuration réseau en 1 clic.',
    p1Title: 'Profils Enregistrés',
    p1Content: 'Cliquez sur Appliquer pour attribuer IP et passerelle.',
    p2Title: 'Créer un Profil',
    p2Content: 'Enregistrez vos IP habituelles.',
    quickipTitle: '🎯 Attribution Rapide d IP',
    quickipDesc: 'Définissez une IP statique en 5 secondes.',
    q1Title: 'Panneau IP Rapide',
    q1Content: 'Saisissez l IP et appliquez immédiatement.',
    q2Title: 'Recherche d IP Libre',
    q2Content: 'Scanne ARP et attribue une IP libre automatiquement.',
    connectivityTitle: '🩺 Diagnostic Ping',
    connectivityDesc: 'Testez la réponse des équipements.',
    c1Title: 'Saisir IP ou Nom d hôte',
    c1Content: 'Testez la connectivité instantanément.',
    c2Title: 'Statut Clair',
    c2Content: 'Badge vert pour une latence optimale.',
    scannerTitle: '🔍 Découverte Réseau',
    scannerDesc: 'Découvrez les équipements sur le réseau.',
    s1Title: 'Scan Réseau en 1 Clic',
    s1Content: 'Calcule le sous-réseau et trouve les équipements actifs.',
    s2Title: 'Identification Constructeur',
    s2Content: 'Identifiez caméras et routeurs via la base OUI.',
    s3Title: 'Copie Rapide',
    s3Content: 'Copiez IP/MAC en un clic.',
    credentialsTitle: '🔑 Bibliothèque d Identifiants',
    credentialsDesc: 'Consultez les mots de passe par défaut des équipements.',
    cr1Title: 'Recherche Instantanée',
    cr1Content: 'Recherchez par marque ou modèle.',
    cr2Title: 'Sécurité et Copie',
    cr2Content: 'Mots de passe masqués avec boutons de copie rapide.',
    clipboardTitle: '📋 Presse-papiers Intelligent',
    clipboardDesc: 'Enregistrez vos commandes et textes fréquents.',
    cl1Title: 'Textes Fréquents',
    cl1Content: 'Cliquez pour copier le texte.',
    internetTitle: '🌐 Statut Internet',
    internetDesc: 'Vérifiez la connexion WAN et l IP publique.',
    in1Title: 'Diagnostic WAN',
    in1Content: 'Testez l accès Internet et la latence DNS.',
    portTitle: '🛡️ Scanner de Ports',
    portDesc: 'Découvrez les ports ouverts et services.',
    po1Title: 'Presets de Ports',
    po1Content: 'Choisissez des presets pour Web, CCTV ou Admin.',
    traceTitle: '🗺️ Traçage de Route',
    traceDesc: 'Découvrez où se situent les ralentissements.',
    tr1Title: 'Onglet Traceroute',
    tr1Content: 'Suivez le chemin vers les routeurs intermédiaires.',
    systemTitle: '💻 Santé du Système',
    systemDesc: 'Surveillez le processeur, la mémoire et les disques.',
    sy1Title: 'Métriques Matérielles',
    sy1Content: 'Suivez les performances du PC en direct.',
    eventsTitle: '⚠️ Journal d Évènements',
    eventsDesc: 'Détectez les erreurs disque et du système Windows.',
    ev1Title: 'Journal d Erreurs',
    ev1Content: 'Filtrez les évènements critiques.',
    shortcutsTitle: '⚙️ Raccourcis & Scripts Windows',
    shortcutsDesc: 'Exécutez flushdns, winsock reset et ouvrez les consoles Windows.',
    sh1Title: 'Outils Système',
    sh1Content: 'Accès direct à ncpa.cpl et scripts système.',
  },

  // ── 中文 ─────────────────────────────────────────────────────────────────────
  zh: {
    welcomeTitle: '👋 欢迎使用 NetMajik',
    welcomeDesc: '了解核心功能以及如何在基础模式和高级模式之间切换。',
    w1Title: '1. 工作模式：基础 vs 高级',
    w1Content: '**基础模式**提供干净安全的操作界面，集成日常常用工具（Ping、扫描、凭据、网卡）。**高级模式**解锁端口扫描、路由追踪和事件查看器等进阶工具。',
    w1Badge: '模式切换',
    w2Title: '2. 连接状态',
    w2Content: '在此查看所有网卡（以太网和 Wi-Fi）、当前 IP 以及当前生效的网络配置文件。',
    w2Badge: '网卡列表',
    w3Title: '3. 快捷工具',
    w3Content: '一键在 Ping 诊断、设备发现、设备凭据和剪贴板之间快速切换。',
    w3Badge: '导航',
    w4Title: '4. 全局搜索 (Ctrl+K)',
    w4Content: '随时按 Ctrl+K 快速查找任何配置、IP 或设备。',
    w4Badge: '高效生产力',
    interfacesTitle: '🌐 网卡与当前配置',
    interfacesDesc: '如何识别网卡状态并查看当前配置。',
    i1Title: '网络适配器',
    i1Content: '已连接网卡会显示绿色状态指示灯。',
    i2Title: '当前配置',
    i2Content: '直观显示处于 DHCP 还是静态配置。',
    profilesTitle: '⚡ 网络配置与 DHCP',
    profilesDesc: '一键快速切换网络 IP 配置。',
    p1Title: '已保存配置列表',
    p1Content: '点击应用即可将网卡快速设置为对应 IP 和网关。',
    p2Title: '创建新配置',
    p2Content: '保存常用 IP 方案，无需手动记忆。',
    quickipTitle: '🎯 快捷 IP 分配',
    quickipDesc: '5 秒内快速设置临时静态 IP。',
    q1Title: '快捷 IP 面板',
    q1Content: '输入目标 IP 并立即生效。',
    q2Title: '一键查找空闲 IP',
    q2Content: 'NetMajik 自动扫描 ARP 并分配未使用 IP。',
    connectivityTitle: '🩺 Ping 与连通性诊断',
    connectivityDesc: '清晰直观测试设备或路由器响应。',
    c1Title: '输入 IP 或主机名',
    c1Content: '输入目标 IP 即可立即开始测试。',
    c2Title: '清晰状态指示',
    c2Content: '绿色徽章显示延迟毫秒数。',
    scannerTitle: '🔍 网络设备扫描',
    scannerDesc: '发现局域网设备、主机名和厂商信息。',
    s1Title: '一键网络扫描',
    s1Content: '自动计算子网范围并查找在线设备。',
    s2Title: '厂商识别',
    s2Content: '基于 OUI 数据库自动识别摄像头、路由器和电脑。',
    s3Title: '快捷复制',
    s3Content: '悬停即可一键复制 IP 或 MAC 地址。',
    credentialsTitle: '🔑 默认凭据库',
    credentialsDesc: '安全查询常用设备的默认账号密码。',
    cr1Title: '即时搜索',
    cr1Content: '按品牌、型号或默认 IP 搜索。',
    cr2Title: '安全与快速复制',
    cr2Content: '密码默认掩码隐藏，支持一键复制。',
    clipboardTitle: '📋 智能剪贴板',
    clipboardDesc: '保存常用命令和文本片段。',
    cl1Title: '常用文本',
    cl1Content: '点击文本卡片即可快速复制。',
    internetTitle: '🌐 外网连接状态',
    internetDesc: '检查路由器外网连接和公网 IP。',
    in1Title: 'WAN 综合诊断',
    in1Content: '测试外网连通性与 DNS 延迟。',
    portTitle: '🛡️ 端口扫描工具',
    portDesc: '扫描设备开放端口与服务。',
    po1Title: '常用端口预设',
    po1Content: '选择 Web、监控摄像头或远程管理预设。',
    traceTitle: '🗺️ 路由追踪 (Traceroute)',
    traceDesc: '查明网络延迟或丢包发生的节点。',
    tr1Title: 'Traceroute 标签页',
    tr1Content: '追踪到达目标地址的每一个中间路由器。',
    systemTitle: '💻 系统与硬件健康',
    systemDesc: '监控 CPU 负载、内存使用率和磁盘。',
    sy1Title: '实时硬件指标',
    sy1Content: '实时掌握系统性能状况。',
    eventsTitle: '⚠️ Windows 事件查看器',
    eventsDesc: '检测磁盘错误和系统崩溃日志。',
    ev1Title: '系统故障日志',
    ev1Content: '筛选关键事件以诊断硬件故障。',
    shortcutsTitle: '⚙️ Windows 快捷工具与脚本',
    shortcutsDesc: '一键清理 DNS、重置 Winsock 和打开控制面板。',
    sh1Title: '系统工具箱',
    sh1Content: '快捷打开 ncpa.cpl、设备管理器和常用脚本。',
  },

  // ── 日本語 ──────────────────────────────────────────────────────────────────
  ja: {
    welcomeTitle: '👋 NetMajikへようこそ',
    welcomeDesc: '基本概念と、基本モードと詳細モードの切り替え方法を説明します。',
    w1Title: '1. 動作モード：基本 vs 詳細',
    w1Content: '**基本モード**は日常の主要ツール（Ping、スキャナー、資格情報、インターフェース）を統合したシンプルで安全な画面です。**詳細モード**はポートスキャン、Traceroute、イベントビューアーなどの専門ツールを有効化します。',
    w1Badge: 'モード制御',
    w2Title: '2. 接続ステータス',
    w2Content: 'すべてのネットワークカード（EthernetおよびWi-Fi）、現在のIP、有効なプロファイルを確認できます。',
    w2Badge: 'インターフェース',
    w3Title: '3. クイックツール',
    w3Content: 'Ping診断、デバイス検出、資格情報、クリップボードの間をワンクリックで切り替えます。',
    w3Badge: 'ナビゲーション',
    w4Title: '4. グローバル検索 (Ctrl+K)',
    w4Content: 'Ctrl+Kを押すことで、プロファイル、IP、デバイスを即座に検索できます。',
    w4Badge: '生産性',
    interfacesTitle: '🌐 インターフェースとアクティブプロファイル',
    interfacesDesc: 'アダプターの識別とアクティブプロファイルの確認。',
    i1Title: 'ネットワークカード',
    i1Content: '接続中は緑色のインジケーターが表示されます。',
    i2Title: 'アクティブプロファイル',
    i2Content: 'DHCPか固定IPプロファイルかを一目で確認できます。',
    profilesTitle: '⚡ ネットワークプロファイルとDHCP',
    profilesDesc: 'ワンクリックでネットワーク設定を切り替えます。',
    p1Title: '保存済みプロファイル一覧',
    p1Content: '適用をクリックするとIPやゲートウェイが即座に設定されます。',
    p2Title: '新規プロファイル作成',
    p2Content: 'よく使うIPを保存して手入力を不要にします。',
    quickipTitle: '🎯 クイックIP割当',
    quickipDesc: '5秒で一時的な固定IPを設定します。',
    q1Title: 'クイックIPパネル',
    q1Content: '希望のIPを入力して即座に適用します。',
    q2Title: '空きIP検索',
    q2Content: 'ARPスキャンを行い、未使用の空きIPを自動割り当てします。',
    connectivityTitle: '🩺 Ping診断と接続確認',
    connectivityDesc: '機器やルーターの応答をわかりやすく確認します。',
    c1Title: 'IPまたはホスト名を入力',
    c1Content: 'IPを入力して応答時間を即座に測定します。',
    c2Title: 'わかりやすいステータス',
    c2Content: '緑色バッジで応答時間（ミリ秒）を表示します。',
    scannerTitle: '🔍 ネットワークスキャン',
    scannerDesc: 'ネットワーク上のデバイスとメーカーを検出します。',
    s1Title: 'ワンクリック・スキャン',
    s1Content: 'サブネットを自動計算しオンライン機器を検索します。',
    s2Title: 'メーカー識別',
    s2Content: 'OUIデータベースによりカメラやルーターのメーカーを自動特定します。',
    s3Title: 'クイックコピー',
    s3Content: 'カーソルを合わせてワンクリックでIPやMACをコピーします。',
    credentialsTitle: '🔑 資格情報ライブラリ',
    credentialsDesc: '機器のデフォルトパスワードを安全に検索します。',
    cr1Title: '即時検索',
    cr1Content: 'ブランド、モデル、標準IPで検索できます。',
    cr2Title: 'セキュリティとコピー',
    cr2Content: 'パスワードはマスク表示され、ワンクリックでコピー可能です。',
    clipboardTitle: '📋 スマート・クリップボード',
    clipboardDesc: 'よく使うコマンドやテキストを保存します。',
    cl1Title: '定型テキスト',
    cl1Content: 'カードをクリックすると即座にクリップボードへコピーされます。',
    internetTitle: '🌐 インターネット接続状態',
    internetDesc: 'ルーターのWAN接続、パブリックIP、ISPを確認します。',
    in1Title: 'WAN総合診断',
    in1Content: 'インターネット接続性とDNSレイテンシを測定します。',
    portTitle: '🛡️ ポートスキャナー',
    portDesc: '開放ポートと稼働サービスを検出します。',
    po1Title: 'ポートプリセット',
    po1Content: 'Web、CCTV、リモート管理用のプリセットを選択できます。',
    traceTitle: '🗺️ 経路追跡 (Traceroute)',
    traceDesc: 'ネットワーク遅延やパケットロスの発生箇所を特定します。',
    tr1Title: 'Tracerouteタブ',
    tr1Content: '目的地までの途中ルーターを順番に追跡します。',
    systemTitle: '💻 システムとハードウェア状態',
    systemDesc: 'CPU使用率、メモリ、ディスク状態を監視します。',
    sy1Title: 'リアルタイム・メトリクス',
    sy1Content: 'PCのパフォーマンスをリアルタイムで監視します。',
    eventsTitle: '⚠️ Windowsイベントログ',
    eventsDesc: 'ディスクエラーやシステムクラッシュを検出します。',
    ev1Title: 'システム障害ログ',
    ev1Content: '重大なイベントをフィルターしてハードウェア問題を診断します。',
    shortcutsTitle: '⚙️ Windows機能とスクリプト',
    shortcutsDesc: 'DNSキャッシュ消去、Winsockリセット、管理ツールを1クリックで実行します。',
    sh1Title: 'システムツール',
    sh1Content: 'ncpa.cplやデバイスマネージャーへ直接アクセスできます。',
  },
};

export const GET_ONBOARDING_TOURS = (language: Language): OnboardingTourConfig[] => {
  const langKey = T[language] ? language : 'en';
  const t = T[langKey];

  return [
    {
      id: 'welcome',
      title: t.welcomeTitle,
      description: t.welcomeDesc,
      iconName: 'Sparkles',
      targetView: 'profiles',
      mode: 'both',
      steps: [
        { targetSelector: '#mode-toggle-btn', title: t.w1Title, content: t.w1Content, badge: t.w1Badge, position: 'bottom' },
        { targetSelector: '#network-interfaces-card', title: t.w2Title, content: t.w2Content, badge: t.w2Badge, position: 'bottom' },
        { targetSelector: '#quick-actions-bar', title: t.w3Title, content: t.w3Content, badge: t.w3Badge, position: 'bottom' },
        { targetSelector: '#global-search-btn', title: t.w4Title, content: t.w4Content, badge: t.w4Badge, position: 'bottom' },
      ],
    },
    {
      id: 'interfaces',
      title: t.interfacesTitle,
      description: t.interfacesDesc,
      iconName: 'Wifi',
      targetView: 'profiles',
      mode: 'both',
      steps: [
        { targetSelector: '#network-interfaces-card', title: t.i1Title, content: t.i1Content, position: 'bottom' },
        { targetSelector: '#active-profile-badge', title: t.i2Title, content: t.i2Content, position: 'bottom' },
      ],
    },
    {
      id: 'profiles',
      title: t.profilesTitle,
      description: t.profilesDesc,
      iconName: 'Sliders',
      targetView: 'profiles',
      mode: 'both',
      steps: [
        { targetSelector: '#profiles-list-container', title: t.p1Title, content: t.p1Content, position: 'bottom' },
        { targetSelector: '#create-profile-btn', title: t.p2Title, content: t.p2Content, position: 'top' },
      ],
    },
    {
      id: 'quickip',
      title: t.quickipTitle,
      description: t.quickipDesc,
      iconName: 'Zap',
      targetView: 'profiles',
      mode: 'both',
      steps: [
        { targetSelector: '#quick-ip-panel', title: t.q1Title, content: t.q1Content, position: 'bottom' },
        { targetSelector: '#free-ip-finder-btn', title: t.q2Title, content: t.q2Content, position: 'top' },
      ],
    },
    {
      id: 'connectivity',
      title: t.connectivityTitle,
      description: t.connectivityDesc,
      iconName: 'Search',
      targetView: 'connectivity',
      mode: 'both',
      steps: [
        { targetSelector: '#ping-input-box', title: t.c1Title, content: t.c1Content, position: 'bottom' },
        { targetSelector: '#ping-status-badge', title: t.c2Title, content: t.c2Content, position: 'top' },
      ],
    },
    {
      id: 'scanner',
      title: t.scannerTitle,
      description: t.scannerDesc,
      iconName: 'Scan',
      targetView: 'scanner',
      mode: 'both',
      steps: [
        { targetSelector: '#scan-start-btn', title: t.s1Title, content: t.s1Content, position: 'bottom' },
        { targetSelector: '#vendor-oui-badge', title: t.s2Title, content: t.s2Content, position: 'top' },
        { targetSelector: '#scanner-results-table', title: t.s3Title, content: t.s3Content, position: 'top' },
      ],
    },
    {
      id: 'credentials',
      title: t.credentialsTitle,
      description: t.credentialsDesc,
      iconName: 'Key',
      targetView: 'credentials',
      mode: 'both',
      steps: [
        { targetSelector: '#credentials-search-input', title: t.cr1Title, content: t.cr1Content, position: 'bottom' },
        { targetSelector: '#credentials-card-list', title: t.cr2Title, content: t.cr2Content, position: 'top' },
      ],
    },
    {
      id: 'clipboard',
      title: t.clipboardTitle,
      description: t.clipboardDesc,
      iconName: 'Clipboard',
      targetView: 'clipboard',
      mode: 'both',
      steps: [
        { targetSelector: '#clipboard-snippets-list', title: t.cl1Title, content: t.cl1Content, position: 'top' },
      ],
    },
    {
      id: 'internet',
      title: t.internetTitle,
      description: t.internetDesc,
      iconName: 'Globe',
      targetView: 'internet',
      mode: 'both',
      steps: [
        { targetSelector: '#internet-status-panel', title: t.in1Title, content: t.in1Content, position: 'top' },
      ],
    },
    {
      id: 'port-scanner',
      title: t.portTitle,
      description: t.portDesc,
      iconName: 'Shield',
      targetView: 'port-scanner',
      mode: 'advanced',
      steps: [
        { targetSelector: '#port-scan-presets', title: t.po1Title, content: t.po1Content, position: 'bottom' },
      ],
    },
    {
      id: 'traceroute',
      title: t.traceTitle,
      description: t.traceDesc,
      iconName: 'Route',
      targetView: 'connectivity',
      mode: 'advanced',
      steps: [
        { targetSelector: '#traceroute-tab-btn', title: t.tr1Title, content: t.tr1Content, position: 'bottom' },
      ],
    },
    {
      id: 'system',
      title: t.systemTitle,
      description: t.systemDesc,
      iconName: 'Activity',
      targetView: 'system',
      mode: 'advanced',
      steps: [
        { targetSelector: '#system-health-grid', title: t.sy1Title, content: t.sy1Content, position: 'top' },
      ],
    },
    {
      id: 'system-events',
      title: t.eventsTitle,
      description: t.eventsDesc,
      iconName: 'AlertTriangle',
      targetView: 'system-events',
      mode: 'advanced',
      steps: [
        { targetSelector: '#system-events-container', title: t.ev1Title, content: t.ev1Content, position: 'top' },
      ],
    },
    {
      id: 'win-shortcuts',
      title: t.shortcutsTitle,
      description: t.shortcutsDesc,
      iconName: 'Sliders',
      targetView: 'win-shortcuts',
      mode: 'advanced',
      steps: [
        { targetSelector: '#win-shortcuts-grid', title: t.sh1Title, content: t.sh1Content, position: 'top' },
      ],
    },
  ];
};

export const getOnboardingTours = GET_ONBOARDING_TOURS;
